"""Python Othello engine with the same contract as the browser engine."""

from .rules import (
    BLACK,
    BOARD_CELLS,
    BOARD_SIZE,
    EMPTY,
    WHITE,
    Move,
    Turn,
    apply_move,
    count_pieces,
    create_initial_board,
    get_flips,
    get_legal_moves,
    get_next_turn,
    index_of,
    is_game_over,
    is_inside,
    legal_action_mask,
    opponent,
    row_col,
    winner,
)

__all__ = [
    "BLACK",
    "BOARD_CELLS",
    "BOARD_SIZE",
    "EMPTY",
    "WHITE",
    "Move",
    "Turn",
    "apply_move",
    "count_pieces",
    "create_initial_board",
    "get_flips",
    "get_legal_moves",
    "get_next_turn",
    "index_of",
    "is_game_over",
    "is_inside",
    "legal_action_mask",
    "opponent",
    "row_col",
    "winner",
]
